### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by Frayzen** [conda-forge/imgui-feedstock#18]
### Comment:

Hello,

First of all, I wanted to thank you for this recipe as I've been using it on my OpenGL project and I was pleased to find it already made in conda forge !
However, I'm currently working on a vulkan project, and it will require Dear ImGUI as well. I figured out that vulkan implementation is not enabled in this recipe. I wonder why ? Is there any specific reason or is it only because no one has never really needed it ?

Adding Dear ImGUI is not too tedious. I'll therefore go for the "by hand" option for the moment but it'd be awesome to have it included in the recipe !

What do you guys think ?

**Comment by traversaro** [comment]
I guess (I am not sure as the original author of the recipe is @Tobias-Fischer ) that vulkan was not enabled just as no one had a direct use for it, but I do not think it would be a problem to enable it. Would you be interested in creating a PR that adds Vulkan support?

**Comment by Tobias-Fischer** [comment]
Yes we’d be very happy to accept pull requests adding Vulkan support

**Comment by Frayzen** [comment]
> Yes we’d be very happy to accept pull requests adding Vulkan support

I just opened [Vulkan Integration](https://github.com/conda-forge/imgui-feedstock/pull/19) !
I'm looking forward for any feedback !
